# understaning when to pass string literals
# base class example from https://mypy.readthedocs.io/en/stable/runtime_troubles.html#future-annotations-import-pep-563
# toggle comments to see 

from __future__ import annotations

# this is fine without passing as string literals as the classes are defined *before* being called.
class B: ...
class C: ...
class A(tuple[B, C]): ... 

# this needs string literals as the classes are defined *after* being called.
class A(tuple['B', 'C']): ... # String literal types needed here
class B: ...
class C: ...
